categories: Kategorie
search: Szukaj
tags: Tagi
tagcloud: "Tag Cloud"
tweets: Tweety
prev: Poprzedni
next: Nastepny
comment: Komentarze
archive_a: Archiwum
archive_b: "Archiwum: %s"
page: "Strona %d"
recent_posts: "Aktualne wpisy"
description: Opis
read_more: "Czytaj wiecej"
links: Linki
about: O mnie
fanpage: Fanpage
about_text: Piotr Trocki
about_text_2: 
	"Pasjonat tanca towarzyskiego. 
	Z tancem zwiazany od 6 roku zycia. 
	Na blogu prezentuje porady dla osob zaintesowanych tańcem oraz zdrowym trybem zycia."
about_img: /blog/img/cutmypic.png